add makefile for installation
gryf/vboxmanage-bash-completion pull request #3
Opened 2018-10-07 13:29 UTC by palortoff

2018-10-08 05:39 UTC, gryf commented on Makefile
> +	@install -v -m 644 VBoxManage  "$(DESTDIR)$(BASHCOMPDIR)/vboxmanage"
How about making soft link instead?

2018-10-15 21:49 UTC, palortoff commented
Yep, softlink would be the better choice. PR updated.

2018-10-16 07:23 UTC, gryf commented
Please, update also README install section for completeness :)

2018-10-16 18:27 UTC, gryf requested changes
I have a doubts regarding install dir and bash-completion package presence. More details in a file comment.

2018-10-16 18:27 UTC, gryf commented on Makefile
> +	@install -v -d "$(DESTDIR)$(BASHCOMPDIR)/"
I'm wondering what value would this Makefile have **without** bash-completion pakage being installed in the system? It doesn't magically appear available in the bash shell. Also, simple check if `$PREFIX/share/bash-completion` exists doesn't do the job right, since it might be installed in different location (i.e. `/usr/local`, `/opt`, `/etc` and so on), not to mention false positive case, where data directory exists, but it's created by something different than bash-completion.

Detecting  bash-completion using package manager is also bad idea for several reasons.
Simplest solution, which comes to my mind is to place on readme file a clear statement, that:
- we expect to have bash-completion installed
- if path to completions differ from `$PREFIX/share/bash-completion/completions` than user/admin should provide right path for completions data.

The latter point will require change in this Makefile, to have PREFIX and BASHCOMPDIR defined to something else, since according to [bash-completion Makefile.am](https://github.com/scop/bash-completion/blob/master/completions/Makefile.am#L1), completion depend on `pkgdatadir` variable, which could be anything :)

2020-06-09 17:20 UTC, gryf commented
No answer for the concerns. Closing.

2020-06-09 17:20 UTC, closed without merging